-- One-time setup
CREATE WAREHOUSE IF NOT EXISTS CI_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS ASSETERA;
CREATE SCHEMA IF NOT EXISTS ASSETERA.PUBLIC;

CREATE ROLE IF NOT EXISTS CI_DEPLOYER;

CREATE USER IF NOT EXISTS github_actions
  PASSWORD = 'StrongPassword123!'
  DEFAULT_ROLE = CI_DEPLOYER
  DEFAULT_WAREHOUSE = CI_WH
  DEFAULT_NAMESPACE = ASSETERA.PUBLIC
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE CI_DEPLOYER TO USER github_actions;

-- Grant required privileges
GRANT USAGE ON WAREHOUSE CI_WH TO ROLE CI_DEPLOYER;
GRANT USAGE ON DATABASE ASSETERA TO ROLE CI_DEPLOYER;
GRANT USAGE ON SCHEMA ASSETERA.PUBLIC TO ROLE CI_DEPLOYER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA ASSETERA.PUBLIC TO ROLE CI_DEPLOYER;
