CREATE DATABASE IF NOT EXISTS ASSETERA;
CREATE SCHEMA IF NOT EXISTS ASSETERA.PUBLIC;
CREATE SCHEMA IF NOT EXISTS UTIL;

CREATE WAREHOUSE IF NOT EXISTS CI_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Registry table for migrations
CREATE TABLE IF NOT EXISTS UTIL.MIGRATIONS_APPLIED (
  FILE_NAME STRING,
  CHECKSUM STRING,
  APPLIED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  APPLIED_BY STRING
);
