CREATE ROLE IF NOT EXISTS CI_DEPLOYER;
CREATE ROLE IF NOT EXISTS ANALYST;
CREATE ROLE IF NOT EXISTS DEVELOPER;

GRANT USAGE ON WAREHOUSE CI_WH TO ROLE CI_DEPLOYER;
GRANT USAGE ON DATABASE ASSETERA TO ROLE CI_DEPLOYER;
GRANT USAGE ON SCHEMA ASSETERA.PUBLIC TO ROLE CI_DEPLOYER;

-- Optional: assign roles to team users
-- GRANT ROLE DEVELOPER TO USER some_user;
-- GRANT ROLE ANALYST TO USER analyst_user;
