CREATE OR REPLACE TABLE FUND_PREDICTIONS_FINAL (
    CUSTOMER_ID NUMBER NOT NULL,
    FUND_ID NUMBER,
    FINAL_RISK NUMBER,
    AGE NUMBER,
    NUMBER_OF_DEPENDENTS NUMBER,
    MARITAL_STATUS STRING,
    GENDER STRING,
    TOTAL_ASSETS NUMBER
);
