-- Snowflake CREATE TABLE for ANSWERS
CREATE OR REPLACE TABLE ANSWERS (
    QUESTION_ID NUMBER NOT NULL,
    ANSWER_ID NUMBER NOT NULL,
    ANSWER_TEXT STRING(128),
    RISK_PROFILE_ID NUMBER,
    PRIMARY KEY (ANSWER_ID, QUESTION_ID),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID),
    FOREIGN KEY (RISK_PROFILE_ID) REFERENCES RISK_PROFILE(RISK_PROFILE_ID)
);

