

-- Snowflake CREATE TABLE for ASSET_CLASS_RETURNS
CREATE TABLE ASSET_CLASS_RETURNS (
    ASSET_CLASS_ID NUMBER NOT NULL,
    ASSET_CLASS_NAME STRING(50),
    AVG_RETURN_10Y NUMBER,
    STD_DEV_10Y NUMBER,
    PRIMARY KEY (ASSET_CLASS_ID)
);



  