

-- Snowflake CREATE TABLE for ASSET_OBJECTIVES
CREATE OR REPLACE TABLE ASSET_OBJECTIVES (
    ASSET_OBJECTIVE_NAME STRING(26),
    ASSET_OBJECTIVE_ID NUMBER NOT NULL,
    PRIMARY KEY (ASSET_OBJECTIVE_ID)
);



  
