

-- Snowflake CREATE TABLE for CUSTOMER_ENGAGEMENT_PREFERENCES
CREATE OR REPLACE TABLE CUSTOMER_ENGAGEMENT_PREFERENCES (
    CUSTOMER_ID NUMBER NOT NULL,
    ENGAGEMENT_TYPE_ID NUMBER,
    FREQUENCY_ID NUMBER,
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (ENGAGEMENT_TYPE_ID) REFERENCES ENGAGEMENT_TYPES(ENGAGEMENT_TYPE_ID),
    FOREIGN KEY (FREQUENCY_ID) REFERENCES ENGAGEMENT_FREQUENCIES(FREQUENCY_ID)
);


