

-- Snowflake CREATE TABLE for CUSTOMER_ANSWERS
CREATE OR REPLACE TABLE CUSTOMER_ANSWERS (
    CUSTOMER_ID NUMBER NOT NULL,
    QUESTION_ID NUMBER NOT NULL,
    ANSWER_ID NUMBER NOT NULL,
    PRIMARY KEY (CUSTOMER_ID, QUESTION_ID),
    FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);


