

-- Snowflake CREATE TABLE for CUSTOMER_ASSETS
CREATE OR REPLACE TABLE CUSTOMER_ASSETS (
    CUSTOMER_ID NUMBER NOT NULL,
    ASSET_OBJECTIVE_ID NUMBER NOT NULL,
    TOTAL STRING(26),
    PRIMARY KEY (CUSTOMER_ID, ASSET_OBJECTIVE_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (ASSET_OBJECTIVE_ID) REFERENCES ASSET_OBJECTIVES(ASSET_OBJECTIVE_ID)
);



 