

-- Snowflake CREATE TABLE for CUSTOMER_FUNDS
CREATE OR REPLACE TABLE CUSTOMER_FUNDS (
    AMOUNT_INVESTED STRING(26),
    CUSTOMER_ID NUMBER NOT NULL,
    FUND_ID NUMBER NOT NULL,
    PRIMARY KEY (CUSTOMER_ID, FUND_ID),
    FOREIGN KEY (FUND_ID) REFERENCES POTENTIAL_FUNDS(FUND_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);


