
-- Snowflake CREATE TABLE for ENGAGEMENT_TYPES
CREATE OR REPLACE TABLE ENGAGEMENT_TYPES (
    ENGAGEMENT_TYPE_NAME STRING(26),
    ENGAGEMENT_TYPE_ID NUMBER NOT NULL,
    PRIMARY KEY (ENGAGEMENT_TYPE_ID)
);


  
