

-- Snowflake CREATE TABLE for ENGAGEMENT_FREQUENCIES
CREATE OR REPLACE TABLE ENGAGEMENT_FREQUENCIES (
    FREQUENCY_NAME STRING(26),
    FREQUENCY_ID NUMBER NOT NULL,
    PRIMARY KEY (FREQUENCY_ID)
);


