
-- Snowflake CREATE TABLE for POTENTIAL_FUNDS
CREATE OR REPLACE TABLE POTENTIAL_FUNDS (
    FUND_NAME STRING(26),
    FUND_DESCRIPTION STRING(26),
    MINIMUM_INVESTMENT_REQUIRED NUMBER,
    MAXIMUM_INVESTMENT_ALLOWED NUMBER,
    FUND_ID NUMBER AUTOINCREMENT PRIMARY KEY
);



