
-- Snowflake CREATE TABLE for POTENTIAL_FUNDS
CREATE TABLE POTENTIAL_FUNDS (
    FUND_NAME STRING(26),
    FUND_DESCRIPTION STRING(26),
    MINIMUM_INVESTMENT_REQUIRED NUMBER,
    MAXIMUM_INVESTMENT_ALLOWED NUMBER,
    FUND_ID NUMBER NOT NULL,
    PRIMARY KEY (FUND_ID)
);



