

-- Snowflake CREATE TABLE for QUESTIONS
CREATE TABLE QUESTIONS (
    QUESTION_SUBJECT STRING(26),
    QUESTION_TEXT STRING(256),
    QUESTION_ID NUMBER NOT NULL,
    PRIMARY KEY (QUESTION_ID)
);



