-- Snowflake CREATE TABLE for US_INCOME_WIDE
CREATE OR REPLACE TABLE US_INCOME_WIDE (
    STATE_NAME STRING(100) NOT NULL,
    STATE_CLEAN STRING(100),
    INCOME_2023 NUMBER,
    INCOME_2022 NUMBER,
    INCOME_2021 NUMBER,
    INCOME_2019 NUMBER,
    INCOME_2018 NUMBER,
    INCOME_2017 NUMBER,
    INCOME_2016 NUMBER,
    INCOME_2015 NUMBER,
    INCOME_2014 NUMBER,
    INCOME_2013 NUMBER,
    GROWTH_RATE_AAGR NUMBER(5,2),
    PRIMARY KEY (STATE_NAME)  -- Note: enforced only as metadata in Snowflake
);
