name: Snowflake Deploy

on:
  push:
    branches: ["*"]   # all branches
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Snowflake Python Connector
        run: pip install snowflake-connector-python

      - name: Run SQL Deployment
        env:
          SNOW_ACCOUNT: ${{ secrets.SNOW_ACCOUNT }}
          SNOW_USER: ${{ secrets.SNOW_USER }}
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
          SNOW_ROLE: ${{ secrets.SNOW_ROLE }}
          SNOW_WAREHOUSE: ${{ secrets.SNOW_WAREHOUSE }}
          SNOW_SCHEMA: ${{ secrets.SNOW_SCHEMA }}
          # 👇 Use clone DB for feature branches, prod DB for main
          SNOW_DATABASE: ${{ github.ref_name == 'main' && secrets.SNOW_DATABASE || secrets.SNOW_DATABASE_DEV }}
        run: python .github/workflows/run_sql.py
